#include "cli.h"

#include <string.h>

#include "FreeRTOS.h"
#include "FreeRTOS_CLI.h"
#include "bsp.h"
#include "debug.h"
#include "stm32g4xx_hal.h"
#include "task.h"

// Send a CLI string to the uart to be printed. Only for use by the CLI
// buf must be of length PRINT_QUEUE_STRING_SIZE (this is always true for CLI
// output buffer)
#define CONSOLE_SEND(buf)                                            \
    do {                                                             \
        xQueueSend(printQueue, buf, PRINT_QUEUE_SEND_TIMEOUT_TICKS); \
        vTaskDelay(1);                                               \
    } while (0)

QueueHandle_t uartRxQueue;

// Buffer to receive uart characters (1 byte)
uint8_t uartDMA_rxBuffer = '\000';
HAL_StatusTypeDef uartStartReceiving(UART_HandleTypeDef* huart) {
    if (huart == &DEBUG_UART_HANDLE) {
        __HAL_UART_FLUSH_DRREGISTER(huart);  // Clear the buffer to prevent overrun
        return HAL_UART_Receive_DMA(huart, &uartDMA_rxBuffer, 1);
    }
    return HAL_ERROR;
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef* huart) {
    BaseType_t xHigherPriorityTaskWoken;

    xHigherPriorityTaskWoken = pdFALSE;

    xQueueSendFromISR(uartRxQueue, &uartDMA_rxBuffer, &xHigherPriorityTaskWoken);

    if (xHigherPriorityTaskWoken) {
        portYIELD();
    }
}

HAL_StatusTypeDef CLI_Init(void) {
    // Initialize the CLI here
    return HAL_OK;
}

#define INPUT_BUFFER_SIZE (100)
#define OUTPUT_BUFFER_SIZE (configCOMMAND_INT_MAX_OUTPUT_SIZE)
static char rxString[INPUT_BUFFER_SIZE];
static int rxIndex = 0;
#ifdef BOARD_NAME
__weak char PS1[] = STRINGIZE(BOARD_NAME) " > ";
#else
__weak char PS1[] = "CLI > ";  // Can override this in project to change PS1
#endif

void cliTask(void* pvParameters) {
    BaseType_t xMoreDataToFollow;
    char* outputBuffer = FreeRTOS_CLIGetOutputBuffer();
    uprintf("CLI Started. Enter command, or help for more info\n");
    uprintf("%s", PS1);

    while (1) {
        char rxBuffer;
        if (xQueueReceive(uartRxQueue, &rxBuffer, portMAX_DELAY) != pdTRUE) {
            uprintf("Error Receiving from UART Rx Queue\n");
            handleError();
        }

        if (rxBuffer == '\n') {
            /* A newline character was received, so the input command string is
            complete and can be processed.  Transmit a line separator, just to
            make the output easier to read. */
            uprintf("\r\n");

            /* The command interpreter is called repeatedly until it returns
            pdFALSE.  See the "Implementing a command" documentation for an
            explanation of why this is. */
            do {
                /* Send the command string to the command interpreter.  Any
                output generated by the command interpreter will be placed in the
                outputBuffer buffer. */
                xMoreDataToFollow = FreeRTOS_CLIProcessCommand(
                    rxString,          /* The command string.*/
                    outputBuffer,      /* The output buffer. */
                    OUTPUT_BUFFER_SIZE /* The size of the output buffer. */
                );

                /* Write the output generated by the command interpreter to the
                console. */
                CONSOLE_SEND(outputBuffer);

            } while (xMoreDataToFollow != pdFALSE);

            uprintf("%s", PS1);

            /* All the strings generated by the input command have been sent.
            Processing of the command is complete.  Clear the input string ready
            to receive the next command. */
            rxIndex = 0;
            memset(rxString, 0x00, INPUT_BUFFER_SIZE);
            memset(outputBuffer, 0x00, OUTPUT_BUFFER_SIZE);
        } else {
            /* The if() clause performs the processing after a newline character
            is received.  This else clause performs the processing if any other
            character is received. */

            if (rxBuffer == '\r') {
                /* Ignore carriage returns. */
            } else if (rxBuffer == '\b') {
                /* Backspace was pressed.  Erase the last character in the input
                buffer - if there are any. */
                if (rxIndex > 0) {
                    rxIndex--;
                    rxString[rxIndex] = '\0';
                }
            } else {
                /* A character was entered.  It was not a new line, backspace
                or carriage return, so it is accepted as part of the input and
                placed into the input buffer.  When a \n is entered the complete
                string will be passed to the command interpreter. */
                if (rxIndex < INPUT_BUFFER_SIZE) {
                    rxString[rxIndex] = rxBuffer;
                    rxIndex++;
                } else {
                    uprintf("Rx string buffer overflow\n");
                }
            }
        }
    }
}